version: "3.9"
services:
  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: task-app
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    expose:
      - "8000"
    ports:
      - 8000:8000
    volumes:
      - ./:/var/www
    networks:
      - app-network
    command: sh -c 'composer install && php artisan serve --host 0.0.0.0'
    depends_on:
      - db

  #MySQL Service
  db:
    image: mysql/mysql-server:latest
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'laravel'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network

#Docker Networks
networks:
  app-network: